vdk-core: add new configuration log_level_module
vmware/versatile-data-kit pull request #1167
Opened 2022-08-31 17:03 UTC by tozka

To enable users to override logs per module, temporarily (e.g for
debugging or prototyping reasons to increase verbosity of certian
module).

The feature works similar to how spring level is specified
(-Dlogging.level.com.baeldung=TRACE)

Configruation is:
'log_level_module="my.module=INFO,my.second.module=debug"'

Testing Done: unit tests

Signed-off-by: Antoni Ivanov <aivanov@vmware.com>

2022-09-01 09:17 UTC, gageorgiev requested changes

2022-09-02 08:00 UTC, tozka commented on projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
> +                result[module_and_level[0]] = {"level": module_and_level[1].upper()}
Yes I will add one. 

I think we need to add support for validation of configuraiton at ConfigurationBuilder level though. It's a little late here. 
The earlier we report the error, the better.

2022-09-02 08:01 UTC, tozka commented on projects/vdk-core/tests/vdk/internal/builtin_plugins/config/test_log_config.py
> +def test_parse_log_level_module():
+1

2022-09-06 16:02 UTC, gageorgiev approved these changes
small formatting details; one error in an exception message; lgtm otherwise

2022-09-06 16:02 UTC, gageorgiev commented on projects/vdk-core/src/vdk/internal/builtin_plugins/config/log_config.py
> +            "Set correctly configuration to log_level_debug configuration in format 'module=level,module2=level2'",
```suggestion
            "Set correctly configuration to log_level_debug configuration in format 'module=level;module2=level2'",
```

2022-09-12 11:50 UTC, merged

2022-09-12 11:50 UTC, tozka commented on projects/vdk-core/src/vdk/internal/builtin_plugins/config/vdk_config.py
> +            " module=level,module2=level2 For example a.b.c=INFO;foo.bar=ERROR "
```suggestion
            " module=level;module2=level2 For example a.b.c=INFO;foo.bar=ERROR "
```