versatile-data-kit: Adding support to read SQM statement as DataFrame
vmware/versatile-data-kit pull request #1292
Opened 2022-11-04 09:24 UTC by victor-partico

#Why
execute_query does not return column name, DataFrames are move useful

#What
Adding new method to job_input

#How has this been tested?
None, could not make build.sh run

#Type
New feature (non-breaking change which adds functionality)

Signed-off-by: Victor Mishovski <vmishovski@vmware.com>

2022-11-04 10:24 UTC, tozka commented
Thanks for the proposal. I do think it's an interesting and important feature to be able to work with Pandas  easily. 

There are a few things though: 

* Маке sure to follow [vmwclabot](https://github.com/vmwclabot) Instructions 

* I recommend having an associated Github issue that explain what and why do we need this . The very least the "Why" section needs to be much more than 1 sentence . See https://github.com/vmware/versatile-data-kit/blob/main/CONTRIBUTING.md#how-to-prepare-your-change

* I am not sure the change should be part of "vdk-core" itself. It introduces a new dependency in vdk-core - "pandas" - and as vdk-core is used in every single plugin and everywhere (vdk related) it needs to have as little dependencies as possible to avoid dependencies conflicts or some variant of [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell). 

You can consider making it a [plugin](https://github.com/vmware/versatile-data-kit/tree/main/projects/vdk-plugins) (vdk-pandas). Changes in vdk-core are much harder to be accepted as they have much bigger impact.
While we welcome all kinds of plugins. 

* Changes in vdk-core and in plugins must be in separate PRs - first for the change in vdk-core and then for the plugins. Though the above point may make this one moot.

2022-11-04 10:26 UTC, tozka commented
Btw the reason build.sh and tests fail (at least what I can see from https://gitlab.com/vmware-analytics/versatile-data-kit/-/jobs/3274269747) is because "ModuleNotFoundError: No module named 'pandas'" 

New dependencies are added in setup.cfg (or setup.py) file in[ install_requires section](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#id5)

2022-11-07 08:05 UTC, ivakoleva requested changes

2022-11-07 08:05 UTC, ivakoleva commented on projects/vdk-core/src/vdk/api/job_input.py
> +            query_result = job_input.execute_query("SELECT * FROM {target_table} WHERE {etl_run_date_column} > now() - interval 2 hours")
include `read_sql_as_dataframe` to the Example usage;
also include into plugin's README.md added

2022-11-07 11:10 UTC, murphp15 commented on projects/vdk-core/src/vdk/internal/builtin_plugins/connection/managed_connection_base.py
> +                res = pd.read_sql(query, con=db)
I would probably just do `return pd.read_sql(query, con=db)` here and then `return None` at the end of the catch statement. But might just be personal preference.

2022-11-07 11:20 UTC, murphp15 commented on projects/vdk-plugins/vdk-postgres/src/vdk/plugin/postgres/postgres_connection.py
> +    def read_sql_as_dataframe(self, query: str) -> List[List[Any]]:
Should the return type not be dataframe?

2022-11-24 09:11 UTC, tozka commented
We talked with Victor and decided we will go with documentation improvement since ultimately this is currently possible with VDK using 
```
pandas.read_sql("select * from x" , job_input.get_managed_connection()) 
```

2022-11-24 09:12 UTC, closed without merging