Add examples for download-job command
vmware/versatile-data-kit pull request #1342
Opened 2022-11-24 13:12 UTC by duyguHsnHsn

2022-11-24 13:24 UTC, gageorgiev approved these changes

2022-11-24 13:36 UTC, doks5 requested changes
Neither the PR, nor any of the commits appear to have any description as to what is being changed.

2022-11-24 16:06 UTC, tozka approved these changes

2022-11-24 17:17 UTC, doks5 approved these changes

2022-11-25 08:33 UTC, tozka commented
Please don't forget the '<artifact/project>:' prefix when merging (https://github.com/vmware/versatile-data-kit/blob/main/support/git-commit-template.txt) We use it when generating release notes.

2022-11-25 09:15 UTC, merged