control-service: errors should be returned to client correcctly
vmware/versatile-data-kit pull request #2415
Opened 2023-07-14 12:26 UTC by murphp15

# Why
At the moment if the kubernetes client throws and error then we assume that the job is not there. 
This is obviously not correct. We should only consider the job not there if it is a 404. 

# What
Now we check to see the status to decide what to do. 

# How was this tested
New unit test which mock k8s responses.

Signed-off-by: murphp15 <murphp15@tcd.ie>

2023-07-14 12:41 UTC, gageorgiev approved these changes

2023-07-14 12:59 UTC, tozka approved these changes

2023-07-14 13:52 UTC, murphp15 commented
Not ready to be merged.

2023-07-14 14:19 UTC, tozka approved these changes

2024-01-16 11:48 UTC, DeltaMichael requested changes
Don't merge this before all the tests run.

2024-03-27 08:36 UTC, closed without merging