add kerberos auth properties to helm chart
vmware/versatile-data-kit pull request #764
Opened 2022-03-10 18:09 UTC by mrMoZ1

what: Added new properties to the helm chart.

why: We are introducing a new KerberosAuthProvider in control-service
and we need to expose configuration properties through the helm chart.

testing: trivial. (deploy a local k8s and make sure values are present)

Signed-off-by: Momchil Zhivkov <mzhivkov@vmware.com>

2022-03-11 10:35 UTC, tozka requested changes

2022-03-17 08:09 UTC, ivakoleva requested changes

2022-03-17 08:09 UTC, ivakoleva commented on projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
> +      keytabFileContents: ""
is it the contents of the same file path? why duplicating configurations?

2022-03-17 08:09 UTC, ivakoleva commented on projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
> +datajobs.security.kerberos.enabled=${SECURITY_KERBEROS_ENABLED:false}
should enabled be enlisted, then the rest of the configs - since enabled is a prerequisite?

2022-03-17 08:09 UTC, ivakoleva commented on projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
> +datajobs.security.kerberos.enabled=${SECURITY_KERBEROS_ENABLED:false}
should enabled be enlisted, then the rest of the configs - since enabled is a prerequisite?

2022-03-17 08:09 UTC, ivakoleva commented on projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
>  #Settings for Kerberos authorization provider.
maybe elaborate on configurations docs?

2022-03-17 08:09 UTC, ivakoleva commented on projects/control-service/projects/pipelines_control_service/src/main/resources/application.properties
>  #Settings for Kerberos authorization provider.
maybe elaborate on configurations docs?

2022-03-17 08:19 UTC, ivakoleva commented
On https://github.com/vmware/versatile-data-kit/pull/764#discussion_r824066630 and https://github.com/vmware/versatile-data-kit/pull/764#discussion_r824067330
you may look for `vdk-options.ini` in projects/control-service/projects/helm_charts for example

2022-03-18 14:05 UTC, tozka commented on projects/control-service/projects/helm_charts/pipelines-control-service/values.yaml
> +      kerberosServicePrincipal: ""
You should explicitly said the principal should have service type "HTTP" aka http/xxx - It's noted in the samples here - https://docs.spring.io/spring-security-kerberos/docs/current/reference/htmlsingle/index.html#samples-sec-server-win-auth but it's easy to miss.

2022-03-18 14:06 UTC, tozka approved these changes
Looks very good to me. Thanks!

You still should take approval from Iva as well.

2022-03-21 08:44 UTC, ivakoleva approved these changes
LGTM

2022-03-21 12:13 UTC, merged