vdk-examples: add ingest and anonymize example
vmware/versatile-data-kit pull request #922
Opened 2022-07-29 06:06 UTC by tozka

The example was inspired by some talks with potential users. But
regardless it's pretty interesting and useful example and added it to
the collection of examples we have. We do not have a lot of examples of
how plugins can be used and this shows they can be pretty powerful.

Signed-off-by: Antoni Ivanov <aivanov@vmware.com>

2022-08-01 19:18 UTC, doks5 requested changes

2022-08-01 19:18 UTC, doks5 commented on examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/setup.py
> +    version="1.0",
Version 1.0?

2022-08-01 19:18 UTC, doks5 commented on examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/src/vdk/plugin/anonymize/anonymization_plugin.py
> +        default_value='{"exchange_rates_series": ["No"]}',
I understand this is a POC plugin, but is this a sensible default?

2022-08-01 19:18 UTC, doks5 commented on examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/src/vdk/plugin/anonymize/ingester_plugin.py
> +import hashlib
nit: Unused import.

2022-08-01 19:18 UTC, doks5 commented on examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/tests/test_anonymization.py
> +def test_anonymization_ingestion():
Not sure why the test, but I guess it could have some value to be present in an e2e example.

2022-08-02 22:30 UTC, tozka commented on examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/tests/test_anonymization.py
> +def test_anonymization_ingestion():
It demonstrates how plugins should be tested. 

The idea of this is to be a tutorial on how to create a (ingest) plugin by using the use case of data anonymization.

2022-08-03 06:06 UTC, doks5 approved these changes
Overall, LGTM

2022-08-03 06:32 UTC, tozka commented on examples/ingest-and-anonymize-plugin/plugins/vdk-poc-anonymize/setup.py
> +    version="1.0",
```suggestion
    version="0.1",
```

2022-08-03 06:34 UTC, merged