vdk-plugins: improve plugin project creation with cookiecutter
vmware/versatile-data-kit pull request #942
Opened 2022-08-17 20:10 UTC by tozka

Add quickstart to make it easier to create a new plugin project with
cookiecutter instead of copy pasting the template folder (which was not
used a lot)

Now it is as easy as

```
pip install -U cookiecutter
cookiecutter https://github.com/tozkata/cookiecutter-vdk-plugin.git
```

Testing Done: 
`cookiecutter https://github.com/tozkata/cookiecutter-vdk-plugin.git`

Signed-off-by: Antoni Ivanov <aivanov@vmware.com>

2022-08-18 11:09 UTC, ivakoleva requested changes

2022-08-18 11:22 UTC, tozka commented on projects/vdk-plugins/README.md
> +cookiecutter https://github.com/tozkata/cookiecutter-vdk-plugin.git
This is the template. It needs to be separate repo, And yes, it's public - https://github.com/tozka/cookiecutter-vdk-plugin.git

2022-08-18 13:44 UTC, ivakoleva commented on projects/vdk-plugins/README.md
> +cookiecutter https://github.com/tozkata/cookiecutter-vdk-plugin.git
Maybe add a sentence about the template repo in the README.md, and the other one you added about plugin code generation?
Will try it and provide feedback; Should we add smoke test coverage?

2022-08-19 15:45 UTC, tozka commented on projects/vdk-plugins/README.md
> +cookiecutter https://github.com/tozkata/cookiecutter-vdk-plugin.git
I don't undertstand about the comment, @ivakoleva 

The template repo is in the README already: in the command: 

Smoke test coverage - probably not now.

2022-08-26 13:38 UTC, gageorgiev approved these changes
Looks good. One thing that worries me is whether it's appropriate to have the template in your personal projects. Could we not rework the current plugin template to be a submodule (https://git.wiki.kernel.org/index.php/GitSubmoduleTutorial) and pass a path to it when creating a plugin?

2022-08-26 13:38 UTC, merged